CREATE TABLE APPOINTMENT (
	APPOINTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PATIENT_ID BIGINT,
    VISIT_TYPE VARCHAR(3),
    CANCEL_DATE TIMESTAMP,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);