CREATE TABLE CONTACT (
	CONTACT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	PATIENT_ID  BIGINT NOT NULL,
    PHONE_NUMBER VARCHAR(16),
    COUNTRY VARCHAR(20),
    CITY VARCHAR(40),
    ADDRESS VARCHAR(60),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);